// Code generated by "stringer -type=FormatAlias -linecomment"; DO NOT EDIT.

package config

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Mp3-1]
	_ = x[Aac-2]
	_ = x[Mp4-3]
	_ = x[Mkv-4]
}

const _FormatAlias_name = "mp3aacmp4mkv"

var _FormatAlias_index = [...]uint8{0, 3, 6, 9, 12}

func (i FormatAlias) String() string {
	idx := int(i) - 1
	if i < 1 || idx >= len(_FormatAlias_index)-1 {
		return "FormatAlias(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _FormatAlias_name[_FormatAlias_index[idx]:_FormatAlias_index[idx+1]]
}
